//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkSystemFinder.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkSystemFinder.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string keyCancel {
            get {
                return ResourceManager.GetString("keyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string keyCloseAll {
            get {
                return ResourceManager.GetString("keyCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string keyCompleted {
            get {
                return ResourceManager.GetString("keyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string keyDark {
            get {
                return ResourceManager.GetString("keyDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string keyDone {
            get {
                return ResourceManager.GetString("keyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string keyError {
            get {
                return ResourceManager.GetString("keyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file has been created! Do you want to open?.
        /// </summary>
        internal static string keyExcelPositive {
            get {
                return ResourceManager.GetString("keyExcelPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string keyFailed {
            get {
                return ResourceManager.GetString("keyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string keyFilter {
            get {
                return ResourceManager.GetString("keyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP End.
        /// </summary>
        internal static string keyIPEnd {
            get {
                return ResourceManager.GetString("keyIPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Start.
        /// </summary>
        internal static string keyIPStart {
            get {
                return ResourceManager.GetString("keyIPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Computers.
        /// </summary>
        internal static string keyLANComputers {
            get {
                return ResourceManager.GetString("keyLANComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string keyLanguage {
            get {
                return ResourceManager.GetString("keyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Printers.
        /// </summary>
        internal static string keyLANPrinters {
            get {
                return ResourceManager.GetString("keyLANPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string keyLight {
            get {
                return ResourceManager.GetString("keyLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string keyLog {
            get {
                return ResourceManager.GetString("keyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string keyMax {
            get {
                return ResourceManager.GetString("keyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string keyMin {
            get {
                return ResourceManager.GetString("keyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Restart!.
        /// </summary>
        internal static string keyNeedRestart {
            get {
                return ResourceManager.GetString("keyNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string keyNo {
            get {
                return ResourceManager.GetString("keyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All.
        /// </summary>
        internal static string keyOpenAll {
            get {
                return ResourceManager.GetString("keyOpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string keyPassword {
            get {
                return ResourceManager.GetString("keyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string keyPC {
            get {
                return ResourceManager.GetString("keyPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Dead IPs.
        /// </summary>
        internal static string keyPingDead {
            get {
                return ResourceManager.GetString("keyPingDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Using Query Command.
        /// </summary>
        internal static string keyQuerySearch {
            get {
                return ResourceManager.GetString("keyQuerySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered IP End.
        /// </summary>
        internal static string keyRemIPEnd {
            get {
                return ResourceManager.GetString("keyRemIPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered IP Start.
        /// </summary>
        internal static string keyRemIPStart {
            get {
                return ResourceManager.GetString("keyRemIPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered Password.
        /// </summary>
        internal static string keyRemPassword {
            get {
                return ResourceManager.GetString("keyRemPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered User.
        /// </summary>
        internal static string keyRemUser {
            get {
                return ResourceManager.GetString("keyRemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve Names.
        /// </summary>
        internal static string keyResolveName {
            get {
                return ResourceManager.GetString("keyResolveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string keyRows {
            get {
                return ResourceManager.GetString("keyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string keySearch {
            get {
                return ResourceManager.GetString("keySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string keySettings {
            get {
                return ResourceManager.GetString("keySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string keyTheme {
            get {
                return ResourceManager.GetString("keyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string keyUser {
            get {
                return ResourceManager.GetString("keyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string keyYes {
            get {
                return ResourceManager.GetString("keyYes", resourceCulture);
            }
        }
    }
}
