//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkSystemFinder.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkSystemFinder.Languages.tr", typeof(tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string keyCancel {
            get {
                return ResourceManager.GetString("keyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitti.
        /// </summary>
        internal static string keyCompleted {
            get {
                return ResourceManager.GetString("keyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karanlık.
        /// </summary>
        internal static string keyDark {
            get {
                return ResourceManager.GetString("keyDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string keyDone {
            get {
                return ResourceManager.GetString("keyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string keyError {
            get {
                return ResourceManager.GetString("keyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel dosyası oluşturuldu! Açmak ister misin?.
        /// </summary>
        internal static string keyExcelPositive {
            get {
                return ResourceManager.GetString("keyExcelPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarısız.
        /// </summary>
        internal static string keyFailed {
            get {
                return ResourceManager.GetString("keyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre.
        /// </summary>
        internal static string keyFilter {
            get {
                return ResourceManager.GetString("keyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Son.
        /// </summary>
        internal static string keyIPEnd {
            get {
                return ResourceManager.GetString("keyIPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Başlangıc.
        /// </summary>
        internal static string keyIPStart {
            get {
                return ResourceManager.GetString("keyIPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerel Bilgisayarlar.
        /// </summary>
        internal static string keyLANComputers {
            get {
                return ResourceManager.GetString("keyLANComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string keyLanguage {
            get {
                return ResourceManager.GetString("keyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerel Yazıcılar.
        /// </summary>
        internal static string keyLANPrinters {
            get {
                return ResourceManager.GetString("keyLANPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık.
        /// </summary>
        internal static string keyLight {
            get {
                return ResourceManager.GetString("keyLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem Kayıt.
        /// </summary>
        internal static string keyLog {
            get {
                return ResourceManager.GetString("keyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum.
        /// </summary>
        internal static string keyMax {
            get {
                return ResourceManager.GetString("keyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string keyMin {
            get {
                return ResourceManager.GetString("keyMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden Başlatılması Gerek!.
        /// </summary>
        internal static string keyNeedRestart {
            get {
                return ResourceManager.GetString("keyNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string keyNo {
            get {
                return ResourceManager.GetString("keyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string keyPassword {
            get {
                return ResourceManager.GetString("keyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisayar.
        /// </summary>
        internal static string keyPC {
            get {
                return ResourceManager.GetString("keyPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölü IP&apos;leri Pingle.
        /// </summary>
        internal static string keyPingDead {
            get {
                return ResourceManager.GetString("keyPingDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlanan IP Sonu.
        /// </summary>
        internal static string keyRemIPEnd {
            get {
                return ResourceManager.GetString("keyRemIPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlanan IP Başlangıçı.
        /// </summary>
        internal static string keyRemIPStart {
            get {
                return ResourceManager.GetString("keyRemIPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlanan Şifre.
        /// </summary>
        internal static string keyRemPassword {
            get {
                return ResourceManager.GetString("keyRemPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlanan Kullanıcı.
        /// </summary>
        internal static string keyRemUser {
            get {
                return ResourceManager.GetString("keyRemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad İste.
        /// </summary>
        internal static string keyResolveName {
            get {
                return ResourceManager.GetString("keyResolveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır.
        /// </summary>
        internal static string keyRows {
            get {
                return ResourceManager.GetString("keyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string keySearch {
            get {
                return ResourceManager.GetString("keySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string keySettings {
            get {
                return ResourceManager.GetString("keySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string keyTheme {
            get {
                return ResourceManager.GetString("keyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        internal static string keyUser {
            get {
                return ResourceManager.GetString("keyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string keyYes {
            get {
                return ResourceManager.GetString("keyYes", resourceCulture);
            }
        }
    }
}
